openshift/ocm-agent-operator

- build/Dockerfile
_(bug)_
This PR would fix the [image test failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/25019/rehearse-25019-pull-ci-openshift-ocm-agent-operator-master-images/1479348178003169280) by updating the Dockerfile
_Fixes #_ https://github.com/openshift/release/pull/25019 
Dockerfile referred from MUO
> Updating Dockerfile to fix image tests

- deploy/50_ocm-agent-operator.Deployment.yaml
- test/deploy/50_ocm-agent-operator.Deployment.yaml
Bug
Fixes invalid affinity settings in the `Deployment` manifest of the OAO.
> Fix broken affinity settings in deployment manifest

- deploy/50_ocm-agent-operator.Deployment.yaml
- test/deploy/50_ocm-agent-operator.Deployment.yaml
Bug
Further fixes from #12 , and also tidies some yamllint problems.
> Fix further broken affinity settings in deployment manifest

- deploy/20_prometheus.Role.yaml
- deploy/20_prometheus.RoleBinding.yaml
- test/deploy/20_prometheus.Role.yaml
- test/deploy/20_prometheus.RoleBinding.yaml
bug
Allow prometheus sa to have resource access in OAO namespace
> Prometheus RBAC for OAO namespace

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_service.go
- pkg/ocmagenthandler/ocmagenthandler_service_test.go
_feature_
build the service for metrics endpoint when the metrics is enabled for ocm-agent
_Fixes #OSD-10056_
> build the service for metrics endpoint

- pkg/apis/ocmagent/v1alpha1/managednotification_types.go
- pkg/apis/ocmagent/v1alpha1/managednotification_types_test.go
_featrue_
Make the fucntion to handle resolve alerts and notifications
Fixes #[OSD-10225](https://issues.redhat.com/browse/OSD-10225)
> [OSD-10225] update CanBeSent func to cover resolved alerts

- pkg/consts/ocmagenthandler/ocmagenthandler.go
Reduce both requests and limits for ocm agent  to match current usage
_(refactor)_
_Fixes #_OSD-10467
> [OSD-10467] Reduce both requests and limits for ocm agent 

- OWNERS
Minor fix
- add user `rendhalver` to reviewers file
_Fixes [OSD-10696](https://issues.redhat.com/browse/OSD-10696)
> OSD-10696 add pete brown to owners file

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_secret_test.go
The PR addresses the gosec lint warnings 
_Fixes #_ [OSD-11460](https://issues.redhat.com/browse/OSD-11460)
> [OSD-11460] Address gosec lint warnings

- OWNERS
_(Add approver)_
Adding myself as an approver as well in addition to existing approvers.
> Adding ravitri as approver

- api/v1alpha1/managedfleetnotificationrecord_types_test.go
- api/v1alpha1/managednotification_types.go
test
- Added test cases to improve coverage.
- Removed dead code function: **NewNotificationRecord**
Fixes : [OSD-15520](https://issues.redhat.com/browse/OSD-15520)
> Implement the unit tests for managedfleetnotification and managednotificationrecord apis

- OWNERS
Adding  Abhishek and Wenqi as approvers.
> Adding Abhishek and Wenqi as approvers for OAO

- pkg/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_networkpolicy.go
- pkg/ocmagenthandler/ocmagenthandler_networkpolicy_test.go
_(feature)_
Implementation of securing communication between MUO and OCM Agent using ingress network policy
https://issues.redhat.com/browse/OSD-19358
https://gitlab.cee.redhat.com/-/snippets/7430
> [OSD-19358] - Adding network policy to allow ingress traffic from MUO

- OWNERS
- build/Dockerfile
- build/Dockerfile.olm-registry
_(bug/feature/cleanup/documentation/test/refactor)_
_Fixes #_
> Add team leads to approvers

- OWNERS
Add more reviewer for the repo as they were working on ocm-agent closely recently
> update reviewer list

- pkg/ocmagenthandler/ocmagenthandler_networkpolicy_test.go
> remove the test print out

- README.md
_(test)_
Triggerring a new build to test the OLM issue
More context: https://redhat-internal.slack.com/archives/CCRND57FW/p1712013165049979
> Trigger a new build to test the OLM issue

- README.md
_(test)_
Just updating the `README.md` to trigger a new build for testing CSV issue.
More context: https://redhat-internal.slack.com/archives/CCRND57FW/p1712013165049979
> Triggering a new build for testing CSV issue

- api/v1alpha1/managednotification_types.go
- deploy/crds/ocmagent.managed.openshift.io_managednotifications.yaml
Bug - update the kubebuilder check as well.
[OHSS-36862](https://issues.redhat.com/browse/OHSS-36862)
> Update the kubebuilder check.

- api/v1alpha1/managednotification_types.go
- api/v1alpha1/managednotification_types_test.go
- build/Dockerfile
- build/Dockerfile.olm-registry
_(bug)_
CanBeSent func return true if the previous ConditionServiceLogSent status is false
_Fixes #_[OSD-20514](https://issues.redhat.com/browse/OSD-20514)
> CanBeSent func return true if the previous ConditionServiceLogSent status is false

- deploy/50_ocm-agent-operator.Deployment.yaml
_(bug)_
Update this operator to the true minimum value i.e. 10m for CPU to avoid discrepancy in the config.
_Fixes #_https://issues.redhat.com/browse/OSD-27575
NA
> Limit set to 10m for CPU

- .tekton/ocm-agent-operator-pull-request.yaml
- .tekton/ocm-agent-operator-push.yaml
Removing the on-cel-expression to fix the jenkins build
> OSD-31062:Removing the on-cel-expression to fix the jenkins build

- .tekton/ocm-agent-operator-e2e-pull-request.yaml
- .tekton/ocm-agent-operator-e2e-push.yaml
updating .tekton e2e files to fix the rpm-scan-issues
> OSD-31018:adding .tekton e2e files
