- .gitignore
Bug
The `.gitignore` has a bit of a legacy `managed-upgrade-operator` reference in it concerning ignoring the `saas-managed-upgrade-operator-bundle`. This corrects that to be `saas-ocm-agent-operator-bundle`.
N/A
> Add saas-ocm-agent-operator-bundle to gitignore

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_deployment.go
- pkg/ocmagenthandler/ocmagenthandler_deployment_test.go
- pkg/ocmagenthandler/ocmagenthandler_service.go
_(feature)_
To make ocm-agent-operator restore the liveliness and readiness probes if it is changed/missing from the deployment
_Fixes #_
[OSD-8943](https://issues.redhat.com/browse/OSD-8943)
This is companion PR for ocm-agent health check as part of [OSD-8943](https://issues.redhat.com/browse/OSD-8943)
> [OSD-8943] add ocm-agent liveliness and readiness probes

- cmd/manager/main.go
- deploy/20_ocm-agent-operator.ClusterRole.yaml
- go.mod
- go.sum
- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_configmap.go
- pkg/ocmagenthandler/ocmagenthandler_configmap_test.go
- test/deploy/20_ocm-agent-operator.ClusterRole.yaml
Feature
OCM Agent requires the cluster's cluster ID in order to send Service Logs to OCM. 
Given the cluster ID is always static, and rather than complicate OCM Agent by having it need to look it up itself, it makes more sense for OCM Agent Operator to collect the cluster ID and populate it for OCM Agent as config.
It will arrive to OCM Agent in the form of a `clusterID` ConfigMap key.
A PR for OCM Agent to acknowledge and read the cluster ID as a config item will arrive separately but is not required for this PR to be merged.
[OSD-10044](https://issues.redhat.com/browse/OSD-10044)
Note that this PR requires additional RBAC if you are testing via an image deployed on-cluster and running as the `ocm-agent-oeprator` ServiceAccount, notably this addition to the `ClusterRole`: …
> OSD-10044 Add cluster ID to OCM Agent config

- pkg/ocmagenthandler/ocmagenthandler_deployment.go
Feature
OCM Agent needs to know the cluster ID; it's currently getting that injected into the ConfigMap used to supply config to the pod; now we need to make the agent aware that it has to read that config.
[OSD-10226](https://issues.redhat.com/browse/OSD-10226)
Do not merge until https://github.com/openshift/ocm-agent/pull/14 is reviewed/merged.
> OSD-10226 Pass cluster ID as parameter to OA

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_configmap.go
- pkg/ocmagenthandler/ocmagenthandler_configmap_test.go
- pkg/ocmagenthandler/ocmagenthandler_deployment.go
- pkg/ocmagenthandler/ocmagenthandler_deployment_test.go
_feature_
mount the trusted ca bundle to the ocm-agent pod which can be used for proxy with user-ca
_Fixes #OSD-9052_
> [OSD-9052] add the configmap for trusted ca bundle, and mount it to deployment

- deploy/20_ocm-agent-operator.ClusterRole.yaml
- docs/design.md
- pkg/consts/controller/controller.go
- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/controller/ocmagent/ocmagent_controller.go
- pkg/ocmagenthandler/ocmagenthandler_deployment.go
- pkg/ocmagenthandler/ocmagenthandler_deployment_test.go
- test/deploy/20_ocm-agent-operator.ClusterRole.yaml
_feature_
Set the env to the ocm agent deployment, so that it can be consumed when the cluster proxy enabled
_Fixes OSD-9052_
> [OSD-9052] fetch the cluster proxy and set them to the deployment

- deploy/20_ocm-agent.Role.yaml
- test/deploy/20_ocm-agent.Role.yaml
Bug
The `ocm-agent` service account is missing permissions to update the `status` of a `managednotification`. This PR adds that permission.
Needed in order to achieve OSD-10224.
> Add missing role permission for ocm-agent SA

- pkg/apis/ocmagent/v1alpha1/managednotification_types.go
- pkg/apis/ocmagent/v1alpha1/managednotification_types_test.go
_feature_
Update the functions which will be used by ocm-agent to update the notification status.
Dependency of https://github.com/openshift/ocm-agent/pull/22
_Fixes #OSD-10340_
> make the SetStatus more configurible and can be used by ocm-agent

- pkg/ocmagenthandler/ocmagenthandler_networkpolicy.go
Bug
`ocm-agent-operator`'s current NetworkPolicy is too broad, it applies to every pod in the namespace.
Mainly this prevents anything from communicating to the `ocm-agent-operator` registry catalog.
We only need the `ocm-agent` NetworkPolicy to apply to the `ocm-agent` pods themselves, so this sets the PodSelector to do exactly that.
> Only apply networkpolicy to ocm-agent pods

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_deployment.go
- pkg/ocmagenthandler/ocmagenthandler_deployment_test.go
As we are going to add new web server running in pod on the infra nodes. It has the risk that the service itself have some performance issue, which may cause the memory or cpu usage issue on that node.
_(feature/refactor)_
Sets Resources.Limits and Resources.Requests for cpu and memory in ocm-agent deployment config
_Fixes #_ [OSD-10467](https://issues.redhat.com/browse/OSD-10467)
> [OSD-10467] Set Resources.Limits and Resources.Requests

- pkg/apis/ocmagent/v1alpha1/managednotification_types.go
_(bug)_
While adding tests, the message was confusing as it searched for notificationrecord but reported notification not found. Small fix in message.
> Changing failure message for notification record not found

- pkg/ocmagenthandler/ocmagenthandler_service.go
Cleanup
Address a gosec linting issue concerning implicit memory aliasing. The code should not use the memory reference of the loop iteration variable. Corrected by assigning to a new variable scoped to the inner loop body.
> Address gosec linting issues

- deploy/50_ocm-agent-operator.Deployment.yaml
**What**: Set CPU and Memory request and limit values for the ocm-agent-operator deployment.
**Why**: ocm-agent-operator should run with specific resource requests and limits to prevent it from consuming too many resources on cluster nodes.
https://issues.redhat.com/browse/OSD-12762
Pre-checks (if applicable):
- Tested changes against a cluster and updated results and screenshots on JIRA ticket.
> added request/limit resources to ocm-agent operator

- api/v1alpha1/managednotification_types.go
- api/v1alpha1/managednotification_types_test.go
- deploy/crds/ocmagent.managed.openshift.io_managednotifications.yaml
feature
To remove the required definition for `resolvedBody` in managednotification.  
This is the first step to make send resolved service log to be optional
_Fixes #_ [OSD-13528](https://issues.redhat.com/browse/OSD-13528)
This change mainly focus on CRD definition
> Remove resolvedBody as required defenition in CRD

- api/v1alpha1/managedfleetnotificationrecord_types.go
Bug
Prevent a panic when checking `CanBeSent` with a FleetNotificationRecord that's never been sent before.
> Prevent panic when checking MFNR send status

- api/v1alpha1/managedfleetnotificationrecord_types.go
- api/v1alpha1/managedfleetnotificationrecord_types_test.go
- controllers/fleetnotification/fleetnotification_controller_suite_test.go
Bug
- Ensures that the object mutating functions for the `ManagedFleetNotificationRecord` type actually modify the object for which the functions are being called.
- Adds unit tests to verify correctness of operation.
> Ensure that API MNFR modifying functions modify the object

- pkg/ocmagenthandler/ocmagenthandler.go
_(bug)_
In fleetmode working of ocm-agent-operator, the secrets required for fleet mode are not created by OAO so shouldn't be deleted by it as well. However, when an instance of `OCMAgent` is deleted that's setup in fleet mode, the associated fleetmode secret is deleted as well. This fix will prevent the fleetmode secrets from being deleted.
_Fixes #_ [OSD-15390](https://issues.redhat.com/browse/OSD-15390)
This bug is was noticed as an extension to the testing work done in [OSD-15390](https://issues.redhat.com/browse/OSD-15390) while adding support for multiple instances of `OCMAgent` and testing it.
> Fixing bug for wrongful deletion of fleet mode secrets

- pkg/ocmagenthandler/ocmagenthandler_deployment.go
Bug
Use the `tokenSecret` value from the `ocmgent` CR as the value used in the `OCM_AGENT_SECRET_NAME` environment variable (instead of the CR name). Otherwise, if a `tokenSecret` value is used which does not match the CR name, the wrong path will be looked up by OCM Agent.
> Ensure tokenSecret value is used for the env var

- controllers/fleetnotification/fleetnotification_controller.go
Bug
The Fleet Controller does not need to care about the deletion of `ManagedFleetNotificationRecord`s, so it is set to be excluded in the event filter.
> Fleet controller should ignore MFNR deletions

- pkg/ocmagenthandler/ocmagenthandler_networkpolicy.go
Bug
The networkpolicy wildcard for fleet mode OAO is not working. Setting it to be the specific namespace to allow.
> Set network policy specific for OAO fleet mode

- pkg/ocmagenthandler/ocmagenthandler_networkpolicy.go
Bug
The fleet mode OCM Agent's networkpolicy needs to allow the `openshift-monitoring` namespace ingress in order for its metrics to be crawled successfully.
> Add openshift-monitoring to fleet-mode networkpolicy

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_networkpolicy.go
- pkg/ocmagenthandler/ocmagenthandler_networkpolicy_test.go
_(bug)_
This PR fixes the bug where multiple instances of OCMAgent for the same mode (default mode or fleet mode) didn't have unique NetworkPolicy resource so far. This PR generalises the name of the networkpolicy such that it starts with the name of the `OCMAgent` resource associated to it and has a suffix based on the mode in which the OCMAgent instance is supposed to operate in.
_Fixes #_ [OSD-15926](https://issues.redhat.com/browse/OSD-15926)
- Ran `curl` for two OCMAgent pods in default mode (each having its unique NetworkPolicy) from `openshift-monitoring` namespace and it worked fine. It failed for both pods when running `curl` from different namespace.
> Generalising networkpolicy name with OCMAgent name and mode suffix

- hack/olm-registry/olm-artifacts-template.yaml
- test/deploy/01_openshift-ocm-agent-operator.Namespace.yaml
bug
This sets pod security admission labels. Currently, none are set and starting with OpenShift 4.13 this generates warnings in Telemetry. This fixes it.
Refer to https://kubernetes.io/docs/concepts/security/pod-security-standards/ to further tighten the labels potentially to the recommended `restricted` level.
The labels were determined by using the https://github.com/stlaz/psachecker tool.
_Fixes #_
> [AUTH-388] set pod security admission labels for namespace

- controllers/ocmagent/ocmagent_controller.go
- deploy/20_ocm-agent-operator.Role.yaml
- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_deployment.go
- pkg/ocmagenthandler/ocmagenthandler_deployment_test.go
- pkg/ocmagenthandler/ocmagenthandler_pdb.go
- pkg/ocmagenthandler/ocmagenthandler_pdb_test.go
_(feature)_
Update the OCM agent deployment configuration to tolerate disruptions, such as infra nodes being terminated to make OCM Agent Highly Available
https://issues.redhat.com/browse/OSD-19745
https://gitlab.cee.redhat.com/-/snippets/7462
> [OSD-19745] - Make OCM Agent Highly Available

- pkg/ocmagenthandler/ocmagenthandler.go
Add logic to create/delete pdb only if the `ocm-agent` service replicas count is set to > 1.
> prevent pdb create/delete if replicas count set to <=1

- build/Dockerfile
- build/Dockerfile.olm-registry
- controllers/fleetnotification/fleetnotification_controller.go
- controllers/fleetnotification/fleetnotification_controller_test.go
bug
nil ptr deref when a `managedfleetnotificationrecorditem` has an empty last transition. 
This is currently the case on the rhobs production cluster because it never sends SLs/LS to integration clusters, but also handles the alerts. This results in the last transition timestamp for the integration items to be nil.
Fixes https://issues.redhat.com/browse/OSD-20956
> Fix(OSD-20956): nilptr deref when cleaning up managedfleetrecorditems with an empty LastTransitionTimestamp

- pkg/consts/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler.go
- pkg/ocmagenthandler/ocmagenthandler_networkpolicy.go
- pkg/ocmagenthandler/ocmagenthandler_networkpolicy_test.go
_(feature)_
To move the ocm-agent-fleet to management cluster, the webhookreceiver will need to receive the alert from the alertmanager which is running in the openshift-observability-operator namespace
_Fixes #_
> [OSD-21689] update networkpolicy for ocm-agent fleet mode on management cluster

- pkg/ocmagenthandler/ocmagenthandler_pdb.go
- pkg/ocmagenthandler/ocmagenthandler_pdb_test.go
_(bug)_
Enhance the ensurePDB logic to compare the full PDB Spec"
https://issues.redhat.com/browse/OSD-22774
1. Updated logic has been coverred by test cases
2. Built an OAO image based on this updated PR and tested to run the OAO on my staging `shawn-rosa-dev`
3. Updated the matchLabel field of `app: ocm-agent` to `app: ocm-agent-test` in PDB spec
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
creationTimestamp: "2024-05-15T09:55:06Z"
generation: 3
name: ocm-agent-pdb
namespace: openshift-ocm-agent-operator
ownerReferences:
- apiVersion: ocmagent.managed.openshift.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: OcmAgent
name: ocm-agent
spec:
minAvailable: 1
selector:
matchLabels:
app: ocm-agent-test
```
4. Checked the OAO logs
```
oc logs …
```
> [OSD-22774] - Enhance the ensurePDB logic to compare the full PDB Spec

- api/v1alpha1/managednotification_types.go
The Error and Fatal levels were deprecated and no longer work: see https://gitlab.cee.redhat.com/service/ocm-service-log#severity-levels
Bug
The current ocm-agent-operator version is breaking cluster-syncs across our hives: https://issues.redhat.com/browse/OHSS-36862 
Fixes #[OHSS-36862](https://issues.redhat.com//browse/OHSS-36862)
> Replace severity levels with supported ones.

- osde2e/ocm_agent_operator_tests.go
What type of PR is this?
Feature Enhancement
What this PR does / why we need it?
This PR marks upgrades as "pending" for outdated configurations in the ocm-agent-operator. It ensures that the upgrade process is paused when configurations are outdated or incompatible, preventing potential upgrade failures due to misconfigured settings.
Which Jira/Github issue(s) this PR fixes?
Part of [OSD-26388](https://issues.redhat.com//browse/OSD-26388)
Special notes for your reviewer:
Implemented logic to detect outdated configurations and halt upgrades until the issues are resolved.
Added logging to indicate when an upgrade is marked as pending due to configuration issues.
Tested the changes to confirm that the upgrade is correctly paused when configurations are outdated.
> Mark Upgrade as pending for outdated configurations
